language: php

php:
  - 5.5
  - 5.4

before_script:
 - composer install

script:
  - phpunit --coverage-text --bootstrap tests/bootstrap.php --configuration tests/phpunit.xml

branches:
  only:
    - develop
    - master
