<?php
namespace Nickfan\AppBox\Tests;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-13 at 10:29:17.
 */
class RepositoryTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var Repository
     */
    protected $object;

    protected $confPath = null;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $appPath = realpath(__DIR__ . '/../../../../app');
        $this->confPath = $confPath = $appPath . '/data/conf';
        $this->object = new \Nickfan\AppBox\Config\Repository(null, $confPath);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @covers Nickfan\AppBox\Config\Repository::getVersion
     */
    public function testGetVersion() {
        $this->assertEquals('1.0', \Nickfan\AppBox\Config\Repository::getVersion());
    }

    /**
     * @covers Nickfan\AppBox\Config\Repository::getIncludePath
     */
    public function testGetIncludePath() {
        $this->assertEquals($this->confPath, $this->object->getIncludePath());
    }
}
